# Generated by Django 5.2.3 on 2025-11-09 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nombre', models.CharField(help_text='Nombre identificativo del tipo de contenido', max_length=100, unique=True, verbose_name='Nombre del Tipo de Contenido')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del tipo de contenido', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Contenido',
                'verbose_name_plural': 'Tipos de Contenido',
            },
        ),
    ]
