# Generated by Django 5.2.3 on 2025-10-19 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estado', models.CharField(default='Creado', help_text='Estado de la notificación en este momento histórico', max_length=20, verbose_name='Estado')),
                ('resumen', models.TextField(blank=True, help_text='Resumen del cambio histórico', null=True, verbose_name='Resumen')),
            ],
            options={
                'verbose_name': 'Histórico Notificación',
                'verbose_name_plural': 'Históricos Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_notificacion', models.IntegerField(help_text='Número único de la notificación', unique=True, verbose_name='Número de Notificación')),
                ('asunto', models.CharField(blank=True, help_text='Descripción breve del contenido de la notificación', max_length=255, null=True, verbose_name='Asunto')),
                ('fecha_notificacion', models.DateField(auto_now_add=True, help_text='Fecha y hora en que se recibió la notificación', verbose_name='Fecha de Notificación')),
                ('lleva_respuesta', models.BooleanField(default=False, help_text='Indica si la notificación requiere una respuesta', verbose_name='Lleva Respuesta')),
                ('estado', models.CharField(default='Creado', help_text='Estado actual de la notificación', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_notificacion'],
            },
        ),
    ]
