# Generated by Django 5.2.3 on 2025-11-09 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        ('especialidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró este estado', verbose_name='Fecha')),
                ('resumen', models.TextField(blank=True, help_text='Resumen del cambio histórico', null=True, verbose_name='Resumen')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado de la notificación en este momento histórico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que registró este cambio de estado', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Histórico Notificación',
                'verbose_name_plural': 'Históricos Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_notificacion', models.IntegerField(help_text='Número único de la notificación', unique=True, verbose_name='Número de Notificación')),
                ('asunto', models.CharField(blank=True, help_text='Descripción breve del contenido de la notificación', max_length=255, null=True, verbose_name='Asunto')),
                ('fecha_notificacion', models.DateField(blank=True, help_text='Fecha y hora en que se recibió la notificación', null=True, verbose_name='Fecha de Notificación')),
                ('lleva_respuesta', models.BooleanField(default=False, help_text='Indica si la notificación requiere una respuesta', verbose_name='Lleva Respuesta')),
                ('especialidad', models.ManyToManyField(blank=True, help_text='Especialidades relacionadas con la notificación', related_name='notificacion', to='especialidades.especialidad', verbose_name='Especialidad')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado actual de la notificación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_notificacion'],
            },
        ),
    ]
