# Generated by Django 5.2 on 2025-05-04 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_notificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Notificación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
