# Generated by Django 5.2.3 on 2025-11-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('obra', '0001_initial'),
        ('ordenesdeservicio', '0001_initial'),
        ('tiposdecontenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='numero_orden_respuesta',
            field=models.ForeignKey(blank=True, help_text='Número de la orden de servicio a la que responde esta notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', related_query_name='orden', to='ordenesdeservicio.ordenesservicio', verbose_name='Número de Orden de Respuesta'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='Obra al que pertenece esta notificación', null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo_respuesta',
            field=models.ForeignKey(blank=True, help_text='Tipo de respuesta asociada a la notificación', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposdecontenido.tipocontenido', verbose_name='Tipo de Respuesta'),
        ),
        migrations.AddField(
            model_name='historiconotificacion',
            name='notificacion',
            field=models.ForeignKey(help_text='Notificación a la que pertenece este registro histórico', on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='notificaciones.notificacion', verbose_name='Notificación'),
        ),
    ]
