# Generated by Django 5.2.3 on 2025-06-16 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('tiposderespuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_orden', models.CharField(help_text='Número único de la orden de servicio', max_length=20, unique=True, verbose_name='Número de Orden')),
                ('asunto', models.CharField(blank=True, help_text='Descripción breve del contenido de la notificación', max_length=255, null=True, verbose_name='Asunto')),
                ('fecha_notificacion', models.DateField(auto_now_add=True, help_text='Fecha y hora en que se recibió la notificación', verbose_name='Fecha de Notificación')),
                ('lleva_respuesta', models.BooleanField(default=False, help_text='Indica si la notificación requiere una respuesta', verbose_name='Lleva Respuesta')),
                ('numero_orden_respuesta', models.CharField(blank=True, help_text='Número de la orden de servicio a la que responde esta notificación', max_length=20, null=True, verbose_name='Número de Orden de Respuesta')),
                ('pendiente_respuesta', models.BooleanField(default=True, help_text='Indica si la notificación está pendiente de respuesta', verbose_name='Pendiente de Respuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', help_text='Estado actual de la notificación', max_length=20, verbose_name='Estado')),
                ('tipo_respuesta', models.ForeignKey(blank=True, help_text='Tipo de respuesta asociada a la notificación', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposderespuesta.tipoderespuesta', verbose_name='Tipo de Respuesta')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_notificacion'],
            },
        ),
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
