# Generated by Django 5.2 on 2025-10-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Fecha y hora en que se registró este estado', verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
