# Generated by Django 5.2.3 on 2025-10-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_alter_estado_options'),
        ('notificaciones', '0004_alter_historiconotificacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiconotificacion',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado de la notificación en este momento histórico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la notificación', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado'),
        ),
    ]
