"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(
    __file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--sxfduh$3(a7v+3y*-8a+f@yma9h%pr+1-+(0q#%x#t8m!%mpn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "10.15.27.6",
    "localhost"
]

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuarios'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    'corsheaders',

    # template
    "template",

    # apps
    "apps.comun",
    "apps.ordenesdeservicio",
    "apps.notificaciones",
    "apps.tiposdecontenido",
    "apps.especialidades",
    "apps.obra",
    "apps.usuarios",
    "apps.administrar"
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.15.27.6",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "dbalmest",
        "USER": "almest",
        "PASSWORD": "almest",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Havana'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = 'static/'

# --------------------------------------------------
# 1. Configuración de JWT (SimpleJWT)
# --------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

""" SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'ALGORITHM': 'HS256',
    # << CAMBIA ESTO
    'SIGNING_KEY': 'P@ssw0rd',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
} """

# --------------------------------------------------
# 2. Configuración de LDAP3
# --------------------------------------------------
""" LDAP_SERVER = '10.15.27.202'
LDAP_PORT = 389
LDAP_USE_TLS = False
LDAP_BASE_DN = 'dc=hra,dc=almest,dc=cu'
LDAP_USERS_DN = 'ou=ubi_ra,dc=hra,dc=almest,dc=cu'

# Credenciales de BIND para el Servicio/Admin (para listar y buscar usuarios)
LDAP_BIND_USER = 'cn=ad,ou=ubi_ra,dc=hra,dc=almest,dc=cu'
# << CAMBIA ESTO
LDAP_BIND_PASSWORD = 'NumLock01' """

LDAP_SERVER = '192.168.20.3'
LDAP_PORT = 389
LDAP_USE_TLS = False
LDAP_BASE_DN = 'dc=ecotra,dc=co,dc=cu'
LDAP_USERS_DN = 'cn=users,dc=ecotra,dc=co,dc=cu'

# Credenciales de BIND para el Servicio/Admin (para listar y buscar usuarios)
LDAP_BIND_USER = 'cn=ldap,cn=users,dc=ecotra,dc=co,dc=cu'
# << CAMBIA ESTO
LDAP_BIND_PASSWORD = 'Passw0rd'

# Mapeo de Atributos de AD/LDAP a Django
# Usado para el login userPrincipalName
# {
#    "username": "Administrator",
#    "password": "Acive3371*"
# }

LDAP_USERNAME_ATTR = 'sAMAccountName'
LDAP_FULLNAME_ATTR = 'cn'
LDAP_EMAIL_ATTR = 'userPrincipalName'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # ⚙️ Logger principal de Django (más reservado)
        'django': {
            'handlers': ['console'],
            # muestra solo warnings y errores del framework
            'level': 'WARNING',
            'propagate': False,
        },

        # ⚙️ Logger específico para tu app de órdenes de servicio
        'apps.ordenesdeservicio': {
            'handlers': ['console'],
            # detallado en dev, silencioso en prod
            'level': 'INFO' if DEBUG else 'ERROR',
            'propagate': False,
        },

        # ⚙️ Logger específico para la app de administración (LDAP)
        'apps.administrar': {
            'handlers': ['console'],
            # detallado en dev para debugging LDAP
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },

        # ⚙️ Logger raíz (aplica a todas las demás apps)
        '': {
            'handlers': ['console'],
            'level': 'WARNING' if DEBUG else 'ERROR',
        },
    },
}
