# Generated by Django 5.2.3 on 2025-06-16 00:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Nombre del tipo de respuesta', max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de respuesta', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Respuesta',
                'verbose_name_plural': 'Tipos de Respuesta',
                'ordering': ['-created_at'],
            },
        ),
    ]
