# Generated by Django 5.2.3 on 2025-10-19 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nombre', models.CharField(help_text='Nombre único del rol', max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('username', models.CharField(help_text='Nombre de usuario único', max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('fullname', models.CharField(help_text='Nombre completo del usuario', max_length=255, verbose_name='Nombre Completo')),
                ('active', models.BooleanField(default=False, help_text='Indica si el usuario está activo', verbose_name='Activo')),
                ('proyecto_principal', models.ForeignKey(blank=True, help_text='Proyecto principal al que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto', verbose_name='Proyecto Principal')),
                ('rol', models.ForeignKey(help_text='Rol del usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tipo_permiso', models.CharField(default='lectura', help_text='Tipo de permiso otorgado (lectura, escritura, etc.)', max_length=50, verbose_name='Tipo de Permiso')),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que tiene acceso el usuario', on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(help_text='Usuario al que se le otorgan permisos', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
    ]
