# Generated by Django 5.2.3 on 2025-11-09 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nombre', models.CharField(help_text='Nombre único del rol', max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(help_text='Nombre de usuario único', max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('fullname', models.CharField(help_text='Nombre completo del usuario', max_length=255, verbose_name='Nombre Completo')),
                ('email', models.CharField(blank=True, default='', help_text='Dirección email del usuario', max_length=200, null=True, verbose_name='Correo electronico')),
                ('active', models.BooleanField(default=True, help_text='Indica si el usuario está activo', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('obra_principal', models.ForeignKey(blank=True, help_text='Obra principal al que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Obra Principal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tipo_permiso', models.CharField(default='lectura', help_text='Tipo de permiso otorgado (lectura, escritura, etc.)', max_length=50, verbose_name='Tipo de Permiso')),
                ('obra', models.ForeignKey(help_text='Obra al que tiene acceso el usuario', on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Obra')),
                ('usuario', models.ForeignKey(help_text='Usuario al que se le otorgan permisos', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'unique_together': {('usuario', 'obra')},
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='obras_permitidas',
            field=models.ManyToManyField(help_text='Obras a las que el usuario tiene acceso', related_name='usuarios_permitidos', through='usuarios.Permisos', to='obra.obra', verbose_name='Obras Permitidas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol del usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
