# Generated by Django 5.2 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='obras_permitidas',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='obras_permitidas',
            field=models.ManyToManyField(help_text='Obras a las que el usuario tiene acceso', related_name='usuarios_permitidos', to='obra.obra', verbose_name='Obras Permitidas'),
        ),
    ]
