# Generated by Django 5.2 on 2025-11-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
        ('usuarios', '0002_alter_usuarios_obras_permitidas_delete_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidad.unidad', verbose_name='Unidad'),
        ),
    ]
