# Generated by Django 5.2.3 on 2025-11-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedencia_destino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedenciadestino',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional', unique=True, verbose_name='Descripción'),
        ),
    ]
