# Generated by Django 5.2.3 on 2025-10-19 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estado', models.CharField(default='Creado', help_text='Estado de la orden de servicio en este momento histórico', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró este estado', verbose_name='Fecha')),
                ('resumen', models.TextField(blank=True, help_text='Resumen del cambio histórico', null=True, verbose_name='Resumen')),
            ],
            options={
                'verbose_name': 'Histórico OS',
                'verbose_name_plural': 'Históricos OS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenesServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_orden', models.IntegerField(help_text='Número único de la orden de servicio (auto-incremental)', unique=True, verbose_name='Número de Orden')),
                ('asunto', models.CharField(help_text='Descripción breve del servicio solicitado', max_length=255, verbose_name='Asunto')),
                ('fecha_notificacion', models.DateField(auto_now_add=True, help_text='Fecha y hora en que se notificó la orden de servicio', null=True, verbose_name='Fecha de Notificación')),
                ('estado', models.CharField(default='Creado', help_text='Estado actual de la orden de servicio', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
    ]
