# Generated by Django 5.2.3 on 2025-11-09 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        ('especialidades', '0001_initial'),
        ('notificaciones', '0001_initial'),
        ('obra', '0001_initial'),
        ('tiposdecontenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('numero_orden', models.IntegerField(help_text='Número único de la orden de servicio (auto-incremental)', unique=True, verbose_name='Número de Orden')),
                ('asunto', models.CharField(help_text='Descripción breve del servicio solicitado', max_length=255, verbose_name='Asunto')),
                ('fecha_notificacion', models.DateField(blank=True, help_text='Fecha y hora en que se notificó la orden de servicio', null=True, verbose_name='Fecha de Notificación')),
                ('lleva_respuesta', models.BooleanField(default=False, help_text='Indica si la orden de servicio lleva una respuesta', verbose_name='Lleva Respuesta')),
                ('especialidad', models.ManyToManyField(blank=True, help_text='Especialidad relacionada con la orden de servicio', related_name='ordenes', to='especialidades.especialidad', verbose_name='Especialidad')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado actual de la orden de servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado')),
                ('notificacion', models.ForeignKey(blank=True, help_text='Notificación a la que responde esta orden de servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.notificacion', verbose_name='Notificación')),
                ('obra', models.ForeignKey(blank=True, help_text='Obra al que pertenece esta orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Obra')),
                ('tipo_contenido', models.ForeignKey(blank=True, help_text='Tipo de contenido asociada a la Orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposdecontenido.tipocontenido', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró este estado', verbose_name='Fecha')),
                ('resumen', models.TextField(blank=True, help_text='Resumen del cambio histórico', null=True, verbose_name='Resumen')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado actual de la orden de servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que registró este cambio de estado', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('orden_servicio', models.ForeignKey(help_text='Orden de servicio a la que pertenece este registro histórico', on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ordenesdeservicio.ordenesservicio', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Histórico OS',
                'verbose_name_plural': 'Históricos OS',
                'ordering': ['-fecha'],
            },
        ),
    ]
