# Generated by Django 5.2.3 on 2025-06-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('notificaciones', '0002_notificacion_delete_notificaciones'),
        ('ordenesdeservicio', '0001_initial'),
        ('tiposdecontenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenesservicio',
            options={'verbose_name': 'Orden de Servicio', 'verbose_name_plural': 'Órdenes de Servicio'},
        ),
        migrations.RemoveField(
            model_name='ordenesservicio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordenesservicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ordenesservicio',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='ordenesservicio',
            name='usuario_creador',
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='asunto',
            field=models.CharField(default=None, help_text='Descripción breve del servicio solicitado', max_length=255, verbose_name='Asunto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Especialidad relacionada con la orden de servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialidades.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='notificacion',
            field=models.ForeignKey(blank=True, help_text='Notificación a la que responde esta orden de servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.notificacion', verbose_name='Notificación'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de la orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, help_text='Tipo de contenido relacionado con la orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposdecontenido.tipocontenido', verbose_name='Tipo de Contenido'),
        ),
        migrations.AlterField(
            model_name='ordenesservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', help_text='Estado actual de la orden de servicio', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenesservicio',
            name='fecha_notificacion',
            field=models.DateField(auto_now_add=True, help_text='Fecha y hora en que se notificó la orden de servicio', null=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='ordenesservicio',
            name='numero_orden',
            field=models.CharField(help_text='Número único de la orden de servicio', max_length=20, unique=True, verbose_name='Número de Orden'),
        ),
    ]
