# Generated by Django 5.2.3 on 2025-10-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        ('notificaciones', '0002_initial'),
        ('ordenesdeservicio', '0001_initial'),
        ('proyecto', '0002_initial'),
        ('tiposdecontenido', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoos',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró este cambio de estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='especialidad',
            field=models.ManyToManyField(blank=True, help_text='Especialidad relacionada con la orden de servicio', related_name='ordenes', to='especialidades.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='notificacion',
            field=models.ForeignKey(blank=True, help_text='Notificación a la que responde esta orden de servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.notificacion', verbose_name='Notificación'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, help_text='Tipo de contenido relacionado con la orden de servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='tiposdecontenido.tipocontenido', verbose_name='Tipo de Contenido'),
        ),
        migrations.AddField(
            model_name='historicoos',
            name='orden_servicio',
            field=models.ForeignKey(help_text='Orden de servicio a la que pertenece este registro histórico', on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ordenesdeservicio.ordenesservicio', verbose_name='Orden de Servicio'),
        ),
    ]
