# Generated by Django 5.2.3 on 2025-10-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenesdeservicio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesservicio',
            name='fecha_notificacion',
            field=models.DateField(blank=True, help_text='Fecha y hora en que se notificó la orden de servicio', null=True, verbose_name='Fecha de Notificación'),
        ),
    ]
