# Generated by Django 5.2.3 on 2025-10-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenesdeservicio', '0003_alter_ordenesservicio_fecha_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesservicio',
            name='estado',
            field=models.CharField(default='Creada', help_text='Estado actual de la orden de servicio', max_length=20, verbose_name='Estado'),
        ),
    ]
