# Generated by Django 5.2.3 on 2025-10-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenesdeservicio', '0006_alter_ordenesservicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoos',
            name='estado',
            field=models.CharField(default='Creada', help_text='Estado de la orden de servicio en este momento histórico', max_length=20, verbose_name='Estado'),
        ),
    ]
