# Generated by Django 5.2.3 on 2025-10-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
        ('ordenesdeservicio', '0007_alter_historicoos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoos',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la orden de servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenesservicio',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la orden de servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comun.estado', verbose_name='Estado'),
        ),
    ]
