# Generated by Django 5.2.3 on 2025-11-22 19:21

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedencia_destino', '0001_initial'),
        ('tipo_documento', '0001_initial'),
        ('unidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistro',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('num', models.IntegerField(db_index=True, help_text='Número', verbose_name='Número')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional', verbose_name='Descripción')),
                ('usuario_nombre', models.CharField(blank=True, help_text='Nombre de usuario', max_length=255, null=True, verbose_name='Nombre de usuario')),
                ('unidad_nombre', models.CharField(blank=True, help_text='Nombre de unidad', max_length=255, null=True, verbose_name='Nombre de unidad')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('procedencia_destino', models.ForeignKey(blank=True, db_constraint=False, help_text='Procedencia o destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procedencia_destino.procedenciadestino', verbose_name='Procedencia o destino')),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo_documento.tipodocumento', verbose_name='Tipo de documento')),
                ('unidad', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuarios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='unidad.unidad', verbose_name='Usuario')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuarios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Registro',
                'verbose_name_plural': 'historical Registros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('num', models.IntegerField(help_text='Número', unique=True, verbose_name='Número')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional', verbose_name='Descripción')),
                ('usuario_nombre', models.CharField(blank=True, help_text='Nombre de usuario', max_length=255, null=True, verbose_name='Nombre de usuario')),
                ('unidad_nombre', models.CharField(blank=True, help_text='Nombre de unidad', max_length=255, null=True, verbose_name='Nombre de unidad')),
                ('procedencia_destino', models.ForeignKey(blank=True, help_text='Procedencia o destino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedencia_destino.procedenciadestino', verbose_name='Procedencia o destino')),
                ('tipo_documento', models.ForeignKey(blank=True, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_documento.tipodocumento', verbose_name='Tipo de documento')),
                ('unidad', models.ForeignKey(blank=True, help_text='Usuarios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidad.unidad', verbose_name='Usuario')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuarios', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
