# Generated by Django 5.2.3 on 2025-11-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistro',
            name='unidad',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Unidades', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='unidad.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidades', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidad.unidad', verbose_name='Unidad'),
        ),
    ]
