# Generated by Django 5.2 on 2025-11-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_historicalregistro_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistro',
            name='ent_sal',
            field=models.CharField(blank=True, choices=[('R/E', 'R/E'), ('R/S', 'R/S')], help_text='R/E para Entrada, R/S para Salida', max_length=3, null=True, verbose_name='Entrada/Salida'),
        ),
        migrations.AddField(
            model_name='registro',
            name='ent_sal',
            field=models.CharField(blank=True, choices=[('R/E', 'R/E'), ('R/S', 'R/S')], help_text='R/E para Entrada, R/S para Salida', max_length=3, null=True, verbose_name='Entrada/Salida'),
        ),
    ]
