# Generated by Django 5.2 on 2025-11-23 12:14

import django.core.validators
import rega.registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_historicalregistro_ent_sal_registro_ent_sal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistro',
            name='archivo',
            field=models.TextField(default=None, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='archivo',
            field=models.FileField(default=None, upload_to=rega.registro.models.ruta_archivo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
            preserve_default=False,
        ),
    ]
