# Generated by Django 5.2 on 2025-11-23 12:15

import django.core.validators
import rega.registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_historicalregistro_archivo_registro_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistro',
            name='archivo',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=rega.registro.models.ruta_archivo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
